In [1]:
import torch
import numpy as np

## Tensors

### 初始化Tensor
* 從python 2d list create tensor

In [2]:
data = [[1, 2], [3, 4]]
data_t = torch.tensor(data)
print(data_t)

tensor([[1, 2],
        [3, 4]])


* 從numpy array creat tensor

In [3]:
data = np.array([[2, 3], [4, 5]])
data_t = torch.tensor(data)
print(data_t)

tensor([[2, 3],
        [4, 5]])


* 從其他的tensor 新增 tensor 
會保留給定tensor的形狀

In [4]:
x_ones = torch.ones_like(data_t)
print(x_ones)
x_rand = torch.rand_like(data_t, dtype=torch.float)
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.6299, 0.0899],
        [0.7387, 0.5356]])


* 給特定的shape然後依照不同的方法initialize tensor

In [5]:
shape = (3, 4, )
rand_tensor = torch.rand(shape)
print(f"Random tensor: \n {rand_tensor} \n")
ones_tensor = torch.ones(shape)
print(f"Ones tensor: \n {ones_tensor} \n")
zeros_tensor = torch.zeros(shape)
print(f"Zeros tensor: \n {zeros_tensor} \n")


Random tensor: 
 tensor([[0.2686, 0.0754, 0.5652, 0.4928],
        [0.2882, 0.4228, 0.7676, 0.0309],
        [0.2299, 0.8265, 0.7700, 0.0830]]) 

Ones tensor: 
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) 

Zeros tensor: 
 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]) 



* Attributes of Tensor

In [6]:
tensor = torch.rand(3, 2)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on {tensor.device}")

Shape of tensor: torch.Size([3, 2])
Datatype of tensor: torch.float32
Device tensor is stored on cpu


### Tensor 上的操作
* 更多詳細可以參考tensor api https://pytorch.org/docs/stable/torch.html
* 如果你的電腦有GPU 可透過以下指令將tensor移動到GPU上


In [7]:
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

* 標準的類似numpy 的操作方法

In [8]:
tensor = torch.ones(3, 4)
print(f"first row:: {tensor[0]} \n")
print(f"First column: {tensor[:, 0]} \n")
print(f"Last column: {tensor[:, -1]}\n")
tensor[:, 1] = 3
print(tensor)

first row:: tensor([1., 1., 1., 1.]) 

First column: tensor([1., 1., 1.]) 

Last column: tensor([1., 1., 1.])

tensor([[1., 3., 1., 1.],
        [1., 3., 1., 1.],
        [1., 3., 1., 1.]])


* tensor concatenate

In [9]:
t1 = torch.cat([tensor, tensor, tensor[:, 1:3]], dim=1)
print(t1)

tensor([[1., 3., 1., 1., 1., 3., 1., 1., 3., 1.],
        [1., 3., 1., 1., 1., 3., 1., 1., 3., 1.],
        [1., 3., 1., 1., 1., 3., 1., 1., 3., 1.]])


* 算術運算

In [10]:
# T*(T')
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
print(f"y1: {y1}\n")
print(f"y2: {y2}\n")


y3 = torch.rand_like(tensor)
print(f"y3(before): {y3}\n")
torch.matmul(tensor, tensor.T, out=y3)
print(f"y3(after): {y3}\n")



y1: tensor([[12., 12., 12.],
        [12., 12., 12.],
        [12., 12., 12.]])

y2: tensor([[12., 12., 12.],
        [12., 12., 12.],
        [12., 12., 12.]])

y3(before): tensor([[0.4798, 0.1655, 0.7053, 0.1025],
        [0.3396, 0.7990, 0.9651, 0.9546],
        [0.1785, 0.1438, 0.5225, 0.4650]])

y3(after): tensor([[12., 12., 12.],
        [12., 12., 12.],
        [12., 12., 12.]])



* single-element tensors

In [11]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

18.0 <class 'float'>


* In-place operations

In [12]:
print(f"tensor: {tensor}\n")
tensor.add_(5)
print(tensor)
t = torch.ones(tensor.shape)
tensor.add_(t)
print(tensor)
t = torch.rand(tensor.shape)
print(t)
tensor.add_(t)
print(tensor)

tensor: tensor([[1., 3., 1., 1.],
        [1., 3., 1., 1.],
        [1., 3., 1., 1.]])

tensor([[6., 8., 6., 6.],
        [6., 8., 6., 6.],
        [6., 8., 6., 6.]])
tensor([[7., 9., 7., 7.],
        [7., 9., 7., 7.],
        [7., 9., 7., 7.]])
tensor([[0.3407, 0.4076, 0.5954, 0.2755],
        [0.5551, 0.3990, 0.2661, 0.2119],
        [0.0126, 0.3577, 0.3959, 0.9510]])
tensor([[7.3407, 9.4076, 7.5954, 7.2755],
        [7.5551, 9.3990, 7.2661, 7.2119],
        [7.0126, 9.3577, 7.3959, 7.9510]])


### 與numpy的交互
* tensor to numpy array

In [13]:
t = torch.ones(2, 3)
print(f"t = {t}\n")
n = t.numpy()
print(f"n = {n}\n")

t = tensor([[1., 1., 1.],
        [1., 1., 1.]])

n = [[1. 1. 1.]
 [1. 1. 1.]]



* 改變tensor 也會一併改變numpy array，反之亦然

In [14]:
t.add_(3) # 改變tensor
print(f"t = {t}\n")
print(f"n = {n}\n")
n[1, 1] = 1.3  # 改變numpy array
print(f"t = {t}\n")
print(f"n = {n}\n")

t = tensor([[4., 4., 4.],
        [4., 4., 4.]])

n = [[4. 4. 4.]
 [4. 4. 4.]]

t = tensor([[4.0000, 4.0000, 4.0000],
        [4.0000, 1.3000, 4.0000]])

n = [[4.  4.  4. ]
 [4.  1.3 4. ]]



* Numpy array to tensor

In [15]:
n = np.random.rand(3, 4)
print(f"n = {n}\n")
t = torch.from_numpy(n)
print(f"t = {t}\n")

n = [[0.71294165 0.92864082 0.05406132 0.03826313]
 [0.74717149 0.69086635 0.66446417 0.7531469 ]
 [0.32198239 0.1539131  0.94912415 0.33370072]]

t = tensor([[0.7129, 0.9286, 0.0541, 0.0383],
        [0.7472, 0.6909, 0.6645, 0.7531],
        [0.3220, 0.1539, 0.9491, 0.3337]], dtype=torch.float64)



In [16]:
t.add_(3) # 改變tensor
print(f"t = {t}\n")
print(f"n = {n}\n")
n[1, 1] = 1.3  # 改變numpy array
print(f"t = {t}\n")
print(f"n = {n}\n")

t = tensor([[3.7129, 3.9286, 3.0541, 3.0383],
        [3.7472, 3.6909, 3.6645, 3.7531],
        [3.3220, 3.1539, 3.9491, 3.3337]], dtype=torch.float64)

n = [[3.71294165 3.92864082 3.05406132 3.03826313]
 [3.74717149 3.69086635 3.66446417 3.7531469 ]
 [3.32198239 3.1539131  3.94912415 3.33370072]]

t = tensor([[3.7129, 3.9286, 3.0541, 3.0383],
        [3.7472, 1.3000, 3.6645, 3.7531],
        [3.3220, 3.1539, 3.9491, 3.3337]], dtype=torch.float64)

n = [[3.71294165 3.92864082 3.05406132 3.03826313]
 [3.74717149 1.3        3.66446417 3.7531469 ]
 [3.32198239 3.1539131  3.94912415 3.33370072]]

